# День 01 – Чистка данных I

## 0. Импорт библиотек

In [1]:
import pandas as pd
import numpy as np 

## 1. Загрузка данных

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [32]:
df = pd.read_csv('/content/drive/MyDrive/School21/day01/bank_data_train.csv') 
df.head() 

ID  CR_PROD_CNT_IL  AMOUNT_RUB_CLO_PRC  PRC_ACCEPTS_A_EMAIL_LINK  \
0  477104               0            0.000000                       NaN   
1  378464               0                 NaN                       NaN   
2  511328               0            0.000000                       NaN   
3  472343               0            0.056424                       NaN   
4  503945               0            0.000000                       NaN   

   APP_REGISTR_RGN_CODE  PRC_ACCEPTS_A_POS  PRC_ACCEPTS_A_TK  \
0                  77.0                NaN               NaN   
1                  50.0                NaN               NaN   
2                   NaN                NaN               NaN   
3                  55.0                NaN               NaN   
4                  74.0                NaN               NaN   

   TURNOVER_DYNAMIC_IL_1M  CNT_TRAN_AUT_TENDENCY1M  SUM_TRAN_AUT_TENDENCY1M  \
0                     0.0                 0.833333                 0.914204   
1                     0.0                      NaN                      NaN   
2                     0.0                      NaN                      NaN   
3                     0.0                      NaN                      NaN   
4                     0.0                      NaN                      NaN   

   ...  REST_DYNAMIC_CC_3M  MED_DEBT_PRC_YWZ  LDEAL_ACT_DAYS_PCT_TR3  \
0  ...                 0.0               0.0                 0.05914   
1  ...                 0.0               NaN                     NaN   
2  ...                 0.0               NaN                     NaN   
3  ...                 0.0               NaN                     NaN   
4  ...                 0.0               NaN                     NaN   

  LDEAL_ACT_DAYS_PCT_AAVG  LDEAL_DELINQ_PER_MAXYWZ  TURNOVER_DYNAMIC_CC_3M  \
0                 0.05914                      0.0                     0.0   
1                     NaN                      NaN                     0.0   
2                     NaN                      NaN                     0.0   
3                     NaN                      NaN                     0.0   
4                     NaN                      NaN                     0.0   

   LDEAL_ACT_DAYS_PCT_TR  LDEAL_ACT_DAYS_PCT_TR4  LDEAL_ACT_DAYS_PCT_CURR  \
0                    0.0                     0.0                      0.0   
1                    NaN                     NaN                      NaN   
2                    NaN                     NaN                      NaN   
3                    NaN                     NaN                      NaN   
4                    NaN                     NaN                      NaN   

  TARGET  
0      0  
1      0  
2      0  
3      0  
4      0  

[5 rows x 116 columns]

## 3. Самостоятельная часть

Ниже вам нужно самим почистить датасет в части текстовых полей.

In [33]:
df.select_dtypes(include=[object]).info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 355190 entries, 0 to 355189
Data columns (total 13 columns):
 #   Column                       Non-Null Count   Dtype 
---  ------                       --------------   ----- 
 0   CLNT_TRUST_RELATION          69421 non-null   object
 1   APP_MARITAL_STATUS           68234 non-null   object
 2   APP_KIND_OF_PROP_HABITATION  59361 non-null   object
 3   CLNT_JOB_POSITION_TYPE       44781 non-null   object
 4   CLNT_JOB_POSITION            210811 non-null  object
 5   APP_DRIVING_LICENSE          57257 non-null   object
 6   APP_EDUCATION                68104 non-null   object
 7   APP_TRAVEL_PASS              57257 non-null   object
 8   APP_CAR                      57256 non-null   object
 9   APP_POSITION_TYPE            60545 non-null   object
 10  APP_EMP_TYPE                 67362 non-null   object
 11  APP_COMP_TYPE                67362 non-null   object
 12  PACK                         355190 non-null  object
dtypes: object(13)


In [34]:
df.select_dtypes(include=[object]).dtypes

CLNT_TRUST_RELATION            object
APP_MARITAL_STATUS             object
APP_KIND_OF_PROP_HABITATION    object
CLNT_JOB_POSITION_TYPE         object
CLNT_JOB_POSITION              object
APP_DRIVING_LICENSE            object
APP_EDUCATION                  object
APP_TRAVEL_PASS                object
APP_CAR                        object
APP_POSITION_TYPE              object
APP_EMP_TYPE                   object
APP_COMP_TYPE                  object
PACK                           object
dtype: object

**0   CLNT_TRUST_RELATION**

In [35]:
# уникальные значения в столбце

df.CLNT_TRUST_RELATION.unique()

array(['BROTHER', nan, 'FATHER', 'FRIEND', 'RELATIVE', 'SISTER', 'OTHER',
       'MOTHER', 'DAUGHTER', 'SON', 'Друг', 'Дальний ро', 'Близкий ро',
       'Мать', 'Отец', 'Брат', 'Сестра', 'Дочь', 'Муж', 'Сын', 'мать',
       'Жена'], dtype=object)

In [38]:
# привести к нижнему регистру

df.CLNT_TRUST_RELATION = df.CLNT_TRUST_RELATION.str.lower()
df.CLNT_TRUST_RELATION.unique()

array(['брат', nan, 'отец', 'друг', 'дальний ро', 'сестра', 'other',
       'мать', 'дочь', 'сын', 'близкий ро', 'муж', 'жена'], dtype=object)

In [39]:
# заменить анг. на русское (одни и те же слова)

df.CLNT_TRUST_RELATION.replace(['brother', 'father', 'friend', 'relative', 'sister', 'mother', 'daughter', 'son'],
                               ['брат', 'отец', 'друг', 'дальний ро', 'сестра', 'мать', 'дочь', 'сын'], inplace=True)
df.CLNT_TRUST_RELATION.unique()

array(['брат', nan, 'отец', 'друг', 'дальний ро', 'сестра', 'other',
       'мать', 'дочь', 'сын', 'близкий ро', 'муж', 'жена'], dtype=object)

**1   APP_MARITAL_STATUS**

In [40]:
# уникальные значения в столбце

df.APP_MARITAL_STATUS.unique()

array(['V', 'D', nan, 'M', 'N', 'T', 'W', 'v', 'm', 'd', 't', 'C', ' ',
       'w'], dtype=object)

In [41]:
# привести к нижнему регистру

df.APP_MARITAL_STATUS = df.APP_MARITAL_STATUS.str.lower()
df.APP_MARITAL_STATUS.unique()

array(['v', 'd', nan, 'm', 'n', 't', 'w', 'c', ' '], dtype=object)

In [42]:
# замена ' ' (пробела) на NaN (пустое значение)

df.APP_MARITAL_STATUS.where(df.APP_MARITAL_STATUS.str.replace(' ','').str.isalpha(), np.nan, inplace=True)
df.APP_MARITAL_STATUS.unique()

array(['v', 'd', nan, 'm', 'n', 't', 'w', 'c'], dtype=object)

**2   APP_KIND_OF_PROP_HABITATION**

In [43]:
# уникальные значения в столбце

df.APP_KIND_OF_PROP_HABITATION.unique()

array(['OTHER', 'SO', nan, 'NPRIVAT', 'RENT', 'JO'], dtype=object)

In [44]:
# привести к нижнему регистру

df.APP_KIND_OF_PROP_HABITATION = df.APP_KIND_OF_PROP_HABITATION.str.lower()
df.APP_KIND_OF_PROP_HABITATION.unique()

array(['other', 'so', nan, 'nprivat', 'rent', 'jo'], dtype=object)

**3   CLNT_JOB_POSITION_TYPE**

In [45]:
# уникальные значения в столбце

df.CLNT_JOB_POSITION_TYPE.unique()

array(['TOP_MANAGER', nan, 'MANAGER', 'SPECIALIST', 'SELF_EMPL'],
      dtype=object)

In [46]:
# привести к нижнему регистру

df.CLNT_JOB_POSITION_TYPE = df.CLNT_JOB_POSITION_TYPE.str.lower()
df.CLNT_JOB_POSITION_TYPE.unique()

array(['top_manager', nan, 'manager', 'specialist', 'self_empl'],
      dtype=object)

**4   CLNT_JOB_POSITION** *(п.3 задания: НЕ применять - замена анг. на русское*

In [47]:
# уникальные значения в столбце

df.CLNT_JOB_POSITION.unique()

array(['Директор по развитию бизнеса', 'ЗАМ ДИРЕКТОРА',
       'КОММЕРЧЕСКИЙ ДИРЕКТОР', ..., 'зам.директора ЦБ', 'УЧЕБРЫЙ МАСТЕР',
       'ЗАМ.РУКОВОДИТЕЛЯ АДМИНИСТРАЦИИ'], dtype=object)

In [48]:
# привести к нижнему регистру

df.CLNT_JOB_POSITION = df.CLNT_JOB_POSITION.str.lower()
df.CLNT_JOB_POSITION.unique()

array(['директор по развитию бизнеса', 'зам директора',
       'коммерческий директор', ..., 'зам.директора цб', 'учебрый мастер',
       'зам.руководителя администрации'], dtype=object)

In [49]:
# не видно есть ли пустые значения, выполним команду на замену, если такие имеются

df.CLNT_JOB_POSITION.where(df.CLNT_JOB_POSITION.str.replace(' ','').str.isalpha(), np.nan, inplace=True)
df.CLNT_JOB_POSITION.unique()

array(['директор по развитию бизнеса', 'зам директора',
       'коммерческий директор', ..., 'мастер по', 'контролёр кпво',
       'учебрый мастер'], dtype=object)

**5   APP_DRIVING_LICENSE**

In [50]:
# уникальные значения в столбце

df.APP_DRIVING_LICENSE.unique()

array(['N', 'Y', nan], dtype=object)

In [51]:
# привести к нижнему регистру

df.APP_DRIVING_LICENSE = df.APP_DRIVING_LICENSE.str.lower()
df.APP_DRIVING_LICENSE.unique()

array(['n', 'y', nan], dtype=object)

**6   APP_EDUCATION**

In [52]:
# уникальные значения в столбце

df.APP_EDUCATION.unique()

array(['H', 'HH', nan, 'UH', 'S', 'SS', 'A', 'i', 'h', 'I', 'a', 's',
       'US', 'HI', 'e', 'E', 'AV', 'AC'], dtype=object)

In [53]:
# привести к нижнему регистру

df.APP_EDUCATION = df.APP_EDUCATION.str.lower()
df.APP_EDUCATION.unique()

array(['h', 'hh', nan, 'uh', 's', 'ss', 'a', 'i', 'us', 'hi', 'e', 'av',
       'ac'], dtype=object)

**7   APP_TRAVEL_PASS**

In [54]:
# уникальные значения в столбце

df.APP_TRAVEL_PASS.unique()

array(['Y', 'N', nan], dtype=object)

In [55]:
# привести к нижнему регистру

df.APP_TRAVEL_PASS = df.APP_TRAVEL_PASS.str.lower()
df.APP_TRAVEL_PASS.unique()

array(['y', 'n', nan], dtype=object)

**8   APP_CAR**

In [56]:
# уникальные значения в столбце

df.APP_CAR.unique()

array(['N', 'Y', nan], dtype=object)

In [57]:
# привести к нижнему регистру

df.APP_CAR = df.APP_CAR.str.lower()
df.APP_CAR.unique()

array(['n', 'y', nan], dtype=object)

**9   APP_POSITION_TYPE**

In [58]:
# уникальные значения в столбце

df.APP_POSITION_TYPE.unique()

array(['TOP_MANAGER', 'MANAGER', nan, 'SPECIALIST', 'SELF_EMPL'],
      dtype=object)

In [59]:
# привести к нижнему регистру

df.APP_POSITION_TYPE = df.APP_POSITION_TYPE.str.lower()
df.APP_POSITION_TYPE.unique()

array(['top_manager', 'manager', nan, 'specialist', 'self_empl'],
      dtype=object)

**10  APP_EMP_TYPE**

In [60]:
# уникальные значения в столбце

df.APP_EMP_TYPE.unique()

array(['PRIVATE', nan, 'STATE', 'INTER', 'IP'], dtype=object)

In [61]:
# привести к нижнему регистру

df.APP_EMP_TYPE = df.APP_EMP_TYPE.str.lower()
df.APP_EMP_TYPE.unique()

array(['private', nan, 'state', 'inter', 'ip'], dtype=object)

**11  APP_COMP_TYPE**

In [62]:
# уникальные значения в столбце

df.APP_COMP_TYPE.unique()

array(['PRIVATE', nan, 'STATE', 'INTER', 'IP'], dtype=object)

In [64]:
# привести к нижнему регистру

df.APP_COMP_TYPE = df.APP_EMP_TYPE.str.lower()
df.APP_COMP_TYPE.unique()

array(['private', nan, 'state', 'inter', 'ip'], dtype=object)

**12  PACK - !!! ОСТАВЛЯЕМ В ИСХОДНОМ ВИДЕ (п.5 задания)**

In [65]:
# уникальные значения в столбце

df.PACK.unique()

array(['104', '102', 'K01', '105', '103', 'O01', '301', '107', '101',
       '109', 'M01', '108'], dtype=object)

**Если есть столбцы, которые абсолютно идентичны по своим значениям для одних 
и тех же строк, то оставить только тот столбец, который идет первее. Речь идет только о текстовых полях.**

*1. сравним значения столбцов CLNT_JOB_POSITION_TYPE и APP_POSITION_TYPE*


In [69]:
df.CLNT_JOB_POSITION_TYPE.unique()

array(['top_manager', nan, 'manager', 'specialist', 'self_empl'],
      dtype=object)

In [70]:
df.APP_POSITION_TYPE.unique()

array(['top_manager', 'manager', nan, 'specialist', 'self_empl'],
      dtype=object)

In [71]:
# сортировка

spisok = [x for x in list(df.CLNT_JOB_POSITION_TYPE.unique()) if x == x]
spisok.sort()
spisok

['manager', 'self_empl', 'specialist', 'top_manager']

In [72]:
spisok_с = [x for x in list(df.APP_POSITION_TYPE.unique()) if x == x]
spisok_с.sort()
spisok_с

['manager', 'self_empl', 'specialist', 'top_manager']

In [75]:
# сравним уникальные значения столбцов, по отсортированным данным

spisok == spisok_с

True

In [76]:
# стравним уникальных значений в столбцах

df['CLNT_JOB_POSITION_TYPE'].equals(df['APP_POSITION_TYPE'])

False

*2. сравним значения столбцов APP_EMP_TYPE и APP_COMP_TYPE*

In [77]:
df.APP_EMP_TYPE.unique()

array(['private', nan, 'state', 'inter', 'ip'], dtype=object)

In [78]:
df.APP_COMP_TYPE.unique()

array(['private', nan, 'state', 'inter', 'ip'], dtype=object)

In [79]:
# сравним уникальные значения столбцов

df.APP_EMP_TYPE.unique() == df.APP_COMP_TYPE.unique() # Функция nunique() по умолчанию не учитывает NaN

array([ True, False,  True,  True,  True])

In [80]:
# стравним уникальных значений в столбцах

df['APP_EMP_TYPE'].equals(df['APP_COMP_TYPE'])

True

*   Делаем вывод, что данные стобцы идентичны
*   Оставляем только первый столбец т.е. 'APP_COMP_TYPE'

In [82]:
# удаляем столбец 'APP_COMP_TYPE'

df.drop('APP_COMP_TYPE', axis=1, inplace=True)
df.shape

(355190, 115)

**Отсортируем датасет по возрастанию значений поля ID**

In [83]:
df_sort=df.sort_values('ID')
df_sort

ID  CR_PROD_CNT_IL  AMOUNT_RUB_CLO_PRC  PRC_ACCEPTS_A_EMAIL_LINK  \
33186   146841               0            0.000000                       NaN   
352582  146842               0            0.041033                       NaN   
8730    146843               0            0.006915                       0.0   
353693  146844               0            0.000000                       NaN   
77628   146845               0            0.000000                       NaN   
...        ...             ...                 ...                       ...   
15548   590822               0            0.000000                       0.0   
249546  590823               0            0.000000                       0.0   
156157  590825               0            0.041298                       NaN   
266514  590826               0            0.000000                       NaN   
343926  590828               0            0.000000                       NaN   

        APP_REGISTR_RGN_CODE  PRC_ACCEPTS_A_POS  PRC_ACCEPTS_A_TK  \
33186                    NaN                NaN               NaN   
352582                   NaN                NaN               NaN   
8730                     NaN                0.0               0.0   
353693                   NaN                NaN               NaN   
77628                    NaN                NaN               NaN   
...                      ...                ...               ...   
15548                    NaN                0.0               0.0   
249546                   NaN                0.0               0.0   
156157                   NaN                NaN               NaN   
266514                   NaN                NaN               NaN   
343926                   NaN                NaN               NaN   

        TURNOVER_DYNAMIC_IL_1M  CNT_TRAN_AUT_TENDENCY1M  \
33186                      0.0                      NaN   
352582                     0.0                 0.166667   
8730                       0.0                      NaN   
353693                     0.0                      NaN   
77628                      0.0                      NaN   
...                        ...                      ...   
15548                      0.0                 0.142857   
249546                     0.0                      NaN   
156157                     0.0                 0.089286   
266514                     0.0                      NaN   
343926                     0.0                      NaN   

        SUM_TRAN_AUT_TENDENCY1M  ...  REST_DYNAMIC_CC_3M  MED_DEBT_PRC_YWZ  \
33186                       NaN  ...                 0.0               NaN   
352582                 0.186107  ...                 0.0               NaN   
8730                        NaN  ...                 0.0               NaN   
353693                      NaN  ...                 0.0               NaN   
77628                       NaN  ...                 0.0               NaN   
...                         ...  ...                 ...               ...   
15548                  0.123579  ...                 0.0               0.0   
249546                      NaN  ...                 0.0               NaN   
156157                 0.065293  ...                 0.0               NaN   
266514                      NaN  ...                 0.0               NaN   
343926                      NaN  ...                 0.0               1.0   

        LDEAL_ACT_DAYS_PCT_TR3 LDEAL_ACT_DAYS_PCT_AAVG  \
33186                      NaN                     NaN   
352582                     NaN                     NaN   
8730                       NaN                     NaN   
353693                     NaN                     NaN   
77628                      NaN                     NaN   
...                        ...                     ...   
15548                      0.0                     0.0   
249546                     NaN                     NaN   
156157                     NaN                     NaN

**Нужно загрузить в GIT в папку src получившийся датасет в виде ZIP-архива**

**Датасет должен быть в формате CSV, и файл должен называться d01_dataset.csv** 

In [84]:
df_zip = dict(method='zip',
              archive_name='d01_dataset.csv')  
df_sort.to_csv('/content/drive/MyDrive/School21/day01/d01_dataset.zip', index=False, compression=df_zip)

*ПРОВЕРКА*

In [85]:
df_p = pd.read_csv('/content/drive/MyDrive/School21/day01/d01_dataset.zip')
df_p

ID  CR_PROD_CNT_IL  AMOUNT_RUB_CLO_PRC  PRC_ACCEPTS_A_EMAIL_LINK  \
0       146841               0            0.000000                       NaN   
1       146842               0            0.041033                       NaN   
2       146843               0            0.006915                       0.0   
3       146844               0            0.000000                       NaN   
4       146845               0            0.000000                       NaN   
...        ...             ...                 ...                       ...   
355185  590822               0            0.000000                       0.0   
355186  590823               0            0.000000                       0.0   
355187  590825               0            0.041298                       NaN   
355188  590826               0            0.000000                       NaN   
355189  590828               0            0.000000                       NaN   

        APP_REGISTR_RGN_CODE  PRC_ACCEPTS_A_POS  PRC_ACCEPTS_A_TK  \
0                        NaN                NaN               NaN   
1                        NaN                NaN               NaN   
2                        NaN                0.0               0.0   
3                        NaN                NaN               NaN   
4                        NaN                NaN               NaN   
...                      ...                ...               ...   
355185                   NaN                0.0               0.0   
355186                   NaN                0.0               0.0   
355187                   NaN                NaN               NaN   
355188                   NaN                NaN               NaN   
355189                   NaN                NaN               NaN   

        TURNOVER_DYNAMIC_IL_1M  CNT_TRAN_AUT_TENDENCY1M  \
0                          0.0                      NaN   
1                          0.0                 0.166667   
2                          0.0                      NaN   
3                          0.0                      NaN   
4                          0.0                      NaN   
...                        ...                      ...   
355185                     0.0                 0.142857   
355186                     0.0                      NaN   
355187                     0.0                 0.089286   
355188                     0.0                      NaN   
355189                     0.0                      NaN   

        SUM_TRAN_AUT_TENDENCY1M  ...  REST_DYNAMIC_CC_3M  MED_DEBT_PRC_YWZ  \
0                           NaN  ...                 0.0               NaN   
1                      0.186107  ...                 0.0               NaN   
2                           NaN  ...                 0.0               NaN   
3                           NaN  ...                 0.0               NaN   
4                           NaN  ...                 0.0               NaN   
...                         ...  ...                 ...               ...   
355185                 0.123579  ...                 0.0               0.0   
355186                      NaN  ...                 0.0               NaN   
355187                 0.065293  ...                 0.0               NaN   
355188                      NaN  ...                 0.0               NaN   
355189                      NaN  ...                 0.0               1.0   

        LDEAL_ACT_DAYS_PCT_TR3 LDEAL_ACT_DAYS_PCT_AAVG  \
0                          NaN                     NaN   
1                          NaN                     NaN   
2                          NaN                     NaN   
3                          NaN                     NaN   
4                          NaN                     NaN   
...                        ...                     ...   
355185                     0.0                     0.0   
355186                     NaN                     NaN   
355187                     NaN                     NaN

In [86]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 355190 entries, 0 to 355189
Data columns (total 115 columns):
 #    Column                       Dtype  
---   ------                       -----  
 0    ID                           int64  
 1    CR_PROD_CNT_IL               int64  
 2    AMOUNT_RUB_CLO_PRC           float64
 3    PRC_ACCEPTS_A_EMAIL_LINK     float64
 4    APP_REGISTR_RGN_CODE         float64
 5    PRC_ACCEPTS_A_POS            float64
 6    PRC_ACCEPTS_A_TK             float64
 7    TURNOVER_DYNAMIC_IL_1M       float64
 8    CNT_TRAN_AUT_TENDENCY1M      float64
 9    SUM_TRAN_AUT_TENDENCY1M      float64
 10   AMOUNT_RUB_SUP_PRC           float64
 11   PRC_ACCEPTS_A_AMOBILE        float64
 12   SUM_TRAN_AUT_TENDENCY3M      float64
 13   CLNT_TRUST_RELATION          object 
 14   PRC_ACCEPTS_TK               float64
 15   PRC_ACCEPTS_A_MTP            float64
 16   REST_DYNAMIC_FDEP_1M         float64
 17   CNT_TRAN_AUT_TENDENCY3M      float64
 18   CNT_ACCEPTS_TK        

In [87]:
df_p.CLNT_TRUST_RELATION.unique()

array([nan, 'мать', 'брат', 'друг', 'сестра', 'other', 'дальний ро',
       'дочь', 'сын', 'отец', 'близкий ро', 'муж', 'жена'], dtype=object)

In [102]:
# подсчет кол-ва уникальных значений в столбце, НЕ учитывает NaN

df_p.CLNT_TRUST_RELATION.nunique()

12

In [103]:
# подсчет кол-ва значений в столбце, С учетом NaN

len(df_p.CLNT_TRUST_RELATION.unique())

13

In [88]:
df_p.APP_MARITAL_STATUS.unique()

array([nan, 'd', 'm', 'v', 't', 'n', 'w', 'c'], dtype=object)

In [89]:
df_p.APP_KIND_OF_PROP_HABITATION.unique()

array([nan, 'so', 'rent', 'other', 'jo', 'nprivat'], dtype=object)

In [90]:
df_p.CLNT_JOB_POSITION_TYPE.unique()

array([nan, 'specialist', 'self_empl', 'manager', 'top_manager'],
      dtype=object)

In [91]:
df_p.CLNT_JOB_POSITION.unique()

array(['начальник отдела', nan, 'генеральный директор', ...,
       'эксперт контакт центра', 'прохлдчик',
       'художник компьютерной графики'], dtype=object)

In [92]:
df_p.APP_DRIVING_LICENSE.unique()

array([nan, 'y', 'n'], dtype=object)

In [93]:
df_p.APP_EDUCATION.unique()

array([nan, 's', 'hh', 'h', 'ss', 'uh', 'a', 'i', 'us', 'e', 'hi', 'av',
       'ac'], dtype=object)

In [94]:
df_p.APP_TRAVEL_PASS.unique()

array([nan, 'n', 'y'], dtype=object)

In [95]:
df_p.APP_CAR.unique()

array([nan, 'n', 'y'], dtype=object)

In [96]:
df_p.APP_EMP_TYPE.unique()

array([nan, 'private', 'state', 'ip', 'inter'], dtype=object)

In [98]:
df_p.APP_COMP_TYPE.unique()

AttributeError: ignored

In [99]:
df_p.PACK.unique()

array(['K01', '102', '105', 'O01', '103', '101', '107', '301', '104',
       '108', '109', 'M01'], dtype=object)